name: Deploy Prod
on:
  push:
    branches:
      - prod
jobs:
  build:
    name: Auto Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          port: 22
          command: cd /var/www/ecourse.syahravi.my.id && git pull origin prod
